### ISSUE TITLE
some error report

### ISSUE THREAD

**Issue by smallprogram** [klever1988/cachewrtbuild#1]
Run klever1988/cachewrtbuild@main
  with:
    ccache: true
    toolchain: true
    skip: true
    clean: false
  env:
    REPO_URL: https://github.com/coolsnowwolf/lede
    REPO_BRANCH: master
    FEEDS_CONF: feeds.conf.default
    CONFIG_FILE: config/x64.config
    DIY_P1_SH: diy-part1.sh
    DIY_P2_SH: diy-part2.sh
    UPLOAD_BIN_DIR: false
    UPLOAD_FIRMWARE: true
    UPLOAD_COWTRANSFER: false
    UPLOAD_WETRANSFER: false
    UPLOAD_RELEASE: true
    TZ: Asia/Shanghai
fatal: ambiguous argument 'tools': unknown revision or path not in the working tree.
Error: Command failed: git log --pretty=tformat:"%h" -n1 tools toolchain
fatal: ambiguous argument 'tools': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'

**Comment by klever1988** [comment]
look at this pr
https://github.com/smallprogram/OpenWrtAction/pull/1
