### ISSUE TITLE
能不能失败也备份

### ISSUE THREAD

**Issue by hong0980** [klever1988/cachewrtbuild#10]
大佬能不能第一次Build失败也备份，备份后第二次就快了，谢谢！

**Comment by klever1988** [comment]
插件只能管好被调用的时候做什么 改变不了主脚本的逻辑
github的默认情况是出错就中止工作流程 你要怎么让插件自己跳出来去保存你的文件 因为它又不会被调用
你应该去修改你自己的编译脚本 让它出错了也不要被github认为你的工作流程出错了
