### ISSUE TITLE
请教大佬

### ISSUE THREAD

**Issue by 281677160** [klever1988/cachewrtbuild#9]
请问，如果我想在本地保留缓存，应该保留什么文件呢？我想在本地编译的时候把缓存文件保留起来，然后跟云编译一样，用最新的源码跟插件编译，本地的那些文件应该保留那些文件可以达到保留缓存的效果？

**Comment by klever1988** [comment]
全保留省事
用btrfs+zstd压缩的分区格式 
不会占用多大空间的
